#!/usr/bin/env bash

PATH=${PWD}/node/bin:$PATH
if [ -f node/bin/node ]; then
    echo "Using packaged node"
else
    which node >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "Using system node"
    else
        echo "NodeJS is not installed or found. Please make sure NodeJS is installed on your system"
    fi
fi

case "$1" in
    node_update)
        npm update
        ;;

    node_install)
        npm install
        ;;
    *)
        node scales.js $@
        ;;
esac
