#!/usr/bin/env bash

if [ -f node/bin/node ]; then
    node/bin/node scales.js
else
    which node >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        node scales.js
    else
        echo "NodeJS is not installed or found. Please make sure NodeJS is installed on your system"
    fi
fi